[package]
name = "nexlint"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
camino = { version = "1.0.3", features = ["serde1"] }
debug-ignore = "1.0.1"
determinator = "0.10.0"
guppy = "0.15.0"
hakari = { version = "0.11.0", features = ["cli-support"] }
hex = "0.4.3"
once_cell = "1.7.2"
serde = { version = "1.0.124", features = ["derive"] }
